services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana

    ports:
      - "3000:3000"

    environment:
      GF_SECURITY_ADMIN_PASSWORD: nouvellecle
      GF_SECURITY_ADMIN_USER: admin
      GF_INSTALL_PLUGINS: grafana-piechart-panel,grafana-llm-app
      GF_FEATURE_TOGGLES_ENABLE: "dashgpt"

    volumes:
      - grafana-data:/var/lib/grafana

    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana-data:
