name: Déploiement Automatique Portfolio

on:
  push:
    branches:
      - main # Déclenche l'action à chaque push sur main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code du dépôt
        uses: actions/checkout@v4

      - name: Configurer Node.js
        uses: actions/setup-node@v4
        with:
          node-node: 20
          cache: 'npm'

      - name: Installer les dépendances
        run: npm ci

      - name: Build du projet React/Vite
        run: npm run build

      - name: Configurer GitHub Pages
        uses: actions/configure-pages@v4

      - name: Téléverser le dossier dist
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
